version: "3.8"
services:
  php:
    build: ./php 
    volumes:
      - ../:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mvc-php
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"